name: 'Terraform Deployment'
description: 'Deploying Terraform script'
inputs:
  workdir:  
    description: 'cd Workdir.'
    required: true
  workspace:  
    description: 'Terraform workspace.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workdir }}
    - ${{ inputs.workspace }}